### PR TITLE
Add simple local avatars

### PR DESCRIPTION
**Pull request by pdewouters**
See #7 

Assuming the package will be names `10up/simple-local-avatars` when published
Will need an upstream fix - see https://github.com/humanmade/simple-local-avatars/pull/1

### CODE REVIEW

**Comment by pdewouters** [comment]
I've changed the required version to `2.2` because that seems to be the one that we'll need with the fix I proposed.

**Comment by roborourke** [comment]
**NOTE**: We need to wait until 2.2.0 is released before this can be merged.

**Comment by rmccue** [comment]
2.2 is still not released.

**Comment by tareiking** [comment]
2.2 still not released, however a new issue tracking release requirements is opened on https://github.com/10up/simple-local-avatars/issues/51

**Comment by joehoyle** [comment]
2.2 is now released, so I think this is good to be merged?

**Comment by pdewouters** [comment]
I don't see a 2.2?

**Comment by joehoyle** [comment]
Ah sorry I misread the comment from @adamsilverstein, it seems only the branch has been created https://github.com/10up/simple-local-avatars/tree/release/2.2.0

**Comment by jeffpaul** [comment]
Correct, we're nearing 2.2 release and are doing some final review on adding test coverage to increase our confidence in the release.  If you have opinions on https://github.com/10up/simple-local-avatars/pull/59 then by all means please comment, otherwise we're working to finalize there and get the release out.

**Comment by roborourke** [comment]
Thanks for the update @jeffpaul 👍  Will check it out

**Comment by jeffpaul** [comment]
@roborourke FYI that we're targeting Monday for the 2.2.0 release, apologies for the delay

**Comment by jeffpaul** [comment]
@roborourke note that the 2.2.0 release is now live

**Comment by roborourke** [comment]
@jeffpaul amazing, thanks for letting me know 🥇

**Comment by jazzsequence** [comment]
closing in favor of https://github.com/humanmade/altis-cms/pull/392

**Pull request closed without merging**
