### PR TITLE
Linking the Altis logo in the admin bar to the Dashboard.

### LINKED ISSUE #116: Altis Admin bar button leads nowhere
The button doesn't do anything, and has a normal mouse cursor, which implies broken anchor markup, instead it should lead somewhere useful, such as the About page as standard WP would:

IMG_3737

### PR DESCRIPTION
**Pull request by kevinlangleyjr**
Fixes #116

### CODE REVIEW

**Comment by richardswain** [comment]
This change works OK but causes a reduction in left and right padding on the div.

**Comment by roborourke** [comment]
Cheers for the report @richardswain. Can you update the CSS @kevinlangleyjr? Just to get the logo lined up with the menu item text in the dropdown.

**Comment by roborourke** [comment]
Happy to make the update if you're on to other things btw, just let me know

**Comment by kevinlangleyjr** [comment]
@roborourke sorry, I got pulled onto other things earlier this week. I just updated the styles to match the previous padding.  👍

**Comment by roborourke** [comment]
@kevinlangleyjr no worries at all! Thanks for coming back to it

**Comment by roborourke** [comment]
Looking on my local I can't see the logo anymore on the front end. Not sure what's happened there exactly but maybe related to the conflict in `branding.css`?

**Comment by roborourke** [comment]
Screenshot 2020-02-05 11 53 28
Screenshot 2020-02-05 11 53 14

**Pull request merged**
