### PR TITLE
Add autoloader flag to command

### PR DESCRIPTION
**Pull request by pdewouters**
Fixes https://github.com/humanmade/altis-cms/issues/168

@joehoyle I'm not clear on how to test the second acceptance criteria. Do you mean run the command locally with that parameter? `composer create-project altis/skeleton altis-test --apcu-autoloader`

### CODE REVIEW

**Comment by joehoyle** [comment]
@pdewouters yeah that's what I was thinking, assuming that is a valid param to `create-project` not just `install`.

**Comment by pdewouters** [comment]
Screenshot 2020-07-01 at 16 06 45

Doesn't look like it does

**Comment by joehoyle** [comment]
Ok, in that case I think we just want to confirm everythign works ok if you run `rm -rf vendor ; composer install --apcu-autloader`

**Comment by pdewouters** [comment]
The site loads ok - are there specific tests to run through?

**Comment by joehoyle** [comment]
@pdewouters I think that's all good then!

**Pull request merged**
